# Generated by Django 4.1.6 on 2023-02-03 19:35

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=355)),
                ("destination", models.CharField(max_length=355)),
                ("distance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MyOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=355)),
                (
                    "cost_per_kilo",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("lat", models.CharField(max_length=100)),
                ("lng", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "pickup_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 3, 19, 35, 11, 254221),
                        help_text="Date & Time",
                        null=True,
                    ),
                ),
                (
                    "additional_helpers",
                    models.CharField(
                        choices=[
                            ("0", "Zero"),
                            ("1", "One"),
                            ("2", "Two"),
                            ("3", "Three"),
                        ],
                        default="0",
                        max_length=3,
                    ),
                ),
                ("floors", models.CharField(default=0, max_length=3)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.measurement",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Customer",},
        ),
    ]
