# Generated by Django 4.1.6 on 2023-03-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_additionalinfo_pickup_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="lat",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="measurement",
            name="lng",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
