# Generated by Django 4.1.6 on 2023-03-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_additionalinfo_email_additionalinfo_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalinfo",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
